version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12  
    commands:
      - echo installing terraform
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - terraform --version
      - ls
      - ll 
      - pwd
      - dnf install zip
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - sudo ./aws/install
      - aws --version
      - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
      - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
      - aws configure set region eu-west-1      
      - cd ~/.aws-cicd-pipeline
      - echo Installing Mocha...
      - npm install -g mocha
      - echo Installing chai...
      - npm install -g chai
      - echo Installing mochawesome...
      - npm install -g mochawesome
      - echo Installing chai-json-schema...
      - npm install -g chai-json-schema
      - echo Installing supertest...
      - npm install -g supertest
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install unit.js      
      - terraform init
      - terraform validate
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code      
      - mocha test.js
      - echo npn run test
      - terraform plan
      #- npm run test
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages 
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - app.js
    - index.html
    - package.json
    - node_modules/async/*
    - node_modules/lodash/*
